export const API_SUFFIX = {
  AUTH: "/auth",
  ADMIN: "/admin",
  USER: "/users",
  REPORT: "/user-reports",
  NOTIFICATION: "/notifications",
  CLASSROOM: "/classrooms",
  QUESTION_BANK: "/question-banks",
  ASSIGNMENT: "/assignments",
  DRAFT_SESSION: "/draft-sessions",
  POST: "/posts",
  COMMENT: "/comments",
  SCHEDULE: "/classrooms",
  ATTENDANCE: "/attendance",
  MATERIAL: "/materials",
  FOLDER: "/folders",
  SUBSCRIPTION: "/subscriptions",
  BENEFIT: "/benefits",
  PLAN: "/plans",
  PAYMENT: "/payments",
};
