export const API_SUFFIX = {
  AUTH: "/auth",
  ADMIN:"/admin",
  USER: "/users",
  CLASSROOM: "/classrooms",
  QUESTION_BANK: "/question-banks",
  POST:      '/posts',
  COMMENT:   '/comments',
  SCHEDULE:  '/classrooms',
  ATTENDANCE:'/attendance',
  MATERIAL:  '/materials',
  FOLDER:    '/folders',
  SUBSCRIPTION: '/subscriptions',
  BENEFIT: '/benefits',
  PLAN: '/plans',
};
